import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

function generateRoomId() {
  // generate a 30 alphanumeric character string room id
  const chars = "0123456789abcdefghijklmnopqrstuvwxyz";
  let roomId = "";
  for (let i = 0; i < 30; i++) {
    roomId += chars[Math.floor(Math.random() * chars.length)];
  }
  return roomId;
}

function randomName() {
  const names = [
    "baleia",
    "golfinho",
    "cavalo",
    "cachorro",
    "gato",
    "elefante",
    "leão",
    "macaco",
    "papagaio",
    "pato",
    "pinguim",
    "tartaruga",
    "urso",
    "vaca",
    "zebra",
    "cavalo",
    "cachorro",
    "gato",
    "elefante",
    "leão",
    "macaco",
    "papagaio",
    "pato",
    "pinguim",
    "tartaruga",
    "urso",
    "vaca",
    "zebra",
  ];
  return names[Math.floor(Math.random() * names.length)];
}

export default function Hame() {
  const [roomId, setRoomId] = useState("");
  const [name, setName] = useState(randomName());

  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <h1 className={"title"}>Quem sou eu ?!</h1>

        <div className={"panel"}>
          <div className={"card"}>
            <h2>Name</h2>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>

          <Link href={`/${generateRoomId()}?name=${name}`}>
            <a className={"card"}>
              <h2>Nova sala &rarr;</h2>
              <p>
                Crie uma nova sala para jogar Quem sou eu ?! com seus amigos.
              </p>
            </a>
          </Link>

          <Link href={`/${roomId}?name=${name}`}>
            <a className={"card"}>
              <h2>Entrar &rarr;</h2>
              <p>Seu amigo criou uma sala? Junte-se agora :)</p>
              <input
                type="text"
                placeholder="Room ID"
                value={roomId}
                onChange={(e) => setRoomId(e.target.value)}
              />
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
